import { app, BrowserWindow, dialog, ipcMain } from "electron";
import * as path from "path";
import { spawn, ChildProcess } from "child_process";
import * as fs from "fs";


let mainWindow: BrowserWindow | null = null;
let apiProcess: ChildProcess | null = null;

// --- Helper: Path Resolution ---
const isDev = !app.isPackaged;

const getBinPath = () => {
  if (isDev) {
    // In dev, we look for python in the environment
    return process.platform === "win32" ? "python" : "python3";
  }
  // In production, point to the executable generated by PyInstaller
  // This assumes you've put your binary in the 'resources' folder
  const binName = process.platform === "win32" ? "api.exe" : "api";
  return path.join(process.resourcesPath, "backend", binName);
};

const getBackendRoot = () => {
  return isDev 
    ? path.join(process.cwd(), "backend") 
    : path.join(process.resourcesPath, "backend");
};

// --- Logging ---
const log = (msg: string) => {
  const logFile = path.join(app.getPath("userData"), "app.log");
  const logMsg = `[${new Date().toISOString()}] ${msg}\n`;
  console.log(logMsg);
  fs.appendFileSync(logFile, logMsg);
};

// --- Backend Management ---
const ensureSSLCerts = async (pythonBin: string, backendDir: string, userDataPath: string): Promise<void> => {
  return new Promise<void>((resolve, reject) => {
    const sslCertDir = path.join(userDataPath, "ssl");
    const certPath = path.join(sslCertDir, "server.crt");
    const keyPath = path.join(sslCertDir, "server.key");

    // Check if certs already exist
    if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
      log("SSL certificates already exist");
      resolve();
      return;
    }

    log("Generating SSL certificates...");

    // Generate certs using Python
    const script = `
import sys
sys.path.insert(0, '${backendDir.replace(/\\/g, '\\\\')}')
import os
os.environ['APP_USER_DATA'] = '${userDataPath.replace(/\\/g, '\\\\')}'
from pathlib import Path
from app.services.ssl_cert import ensure_ssl_certs
ensure_ssl_certs(Path('${sslCertDir.replace(/\\/g, '\\\\')}'))
print('SSL certificates generated successfully')
`;

    const certProcess = spawn(pythonBin, ["-c", script], {
      cwd: backendDir,
      env: { ...process.env, PYTHONUNBUFFERED: "1" },
    });

    certProcess.stdout?.on("data", (data) => log(`[SSL] ${data.toString()}`));
    certProcess.stderr?.on("data", (data) => log(`[SSL] ${data.toString()}`));

    certProcess.on("close", (code) => {
      if (code === 0) {
        log("SSL certificates ready");
        resolve();
      } else {
        reject(new Error(`SSL cert generation failed with code ${code}`));
      }
    });

    certProcess.on("error", reject);
  });
};

const startBackend = async () => {
  return new Promise<void>(async (resolve, reject) => {
    const pythonBin = getBinPath();
    const backendDir = getBackendRoot();
    const userDataPath = app.getPath("userData");

    log(`Starting backend with: ${pythonBin} in ${backendDir}`);
    log(`User Data Path for SQLite: ${userDataPath}`);

    // Fix permissions for macOS/Linux in production before spawning
    if (!isDev && process.platform !== "win32") {
      try {
        log("Ensuring backend binary is executable...");
        fs.chmodSync(pythonBin, 0o755);
      } catch (e: any) {
        log(`Warning: Could not set permissions on binary: ${e.message}`);
      }
    }

    // Ensure SSL certificates exist before starting server
    if (isDev) {
      try {
        await ensureSSLCerts(pythonBin, backendDir, userDataPath);
      } catch (e: any) {
        log(`Warning: Could not generate SSL certs: ${e.message}`);
        // Continue anyway, will try to generate on startup
      }
    }

    let args: string[] = [];
    const sslCertDir = path.join(userDataPath, "ssl");

    if (isDev) {
      // In dev, we run uvicorn directly with SSL enabled
      args = [
        "-m", "uvicorn", "app.main:app",
        "--host", "0.0.0.0",  // Listen on all interfaces for PWA sync
        "--port", "8833",
        "--ssl-keyfile", path.join(sslCertDir, "server.key"),
        "--ssl-certfile", path.join(sslCertDir, "server.crt"),
      ];
    } else {
      args = ["--port", "8833", "--ssl"];  // Production: enable SSL with auto-generated certs
    }

    apiProcess = spawn(pythonBin, args, {
      cwd: backendDir,
      env: { 
        ...process.env, 
        PYTHONUNBUFFERED: "1",
        APP_USER_DATA: userDataPath 
      },
      shell: false 
    });

    // Unified log handler to catch signals regardless of which stream Python uses
    const handleOutput = (data: any) => {
      const output = data.toString();
      log(`[API] ${output}`);

      // We look for "Uvicorn running" OR "Application startup complete" (the FastAPI signal)
      if (output.includes("Uvicorn running") || output.includes("Application startup complete")) {
        log("Backend signal received: Server is ready.");
        resolve();
      }
    };

    apiProcess.stdout?.on("data", handleOutput);
    apiProcess.stderr?.on("data", handleOutput);

    apiProcess.on("error", (err) => {
      log(`Failed to spawn backend: ${err.message}`);
      reject(err);
    });

    // Increased timeout to 30s to account for SQLite migration time on first run
    const startupTimeout = setTimeout(() => {
      log("Backend startup timeout reached. Attempting to load window anyway...");
      resolve();
    }, 30000);

    // Clean up timeout if we resolve early
    apiProcess.on("exit", () => clearTimeout(startupTimeout));
  });
};

// --- Window Management ---
const createWindow = () => {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    webPreferences: {
      contextIsolation: true,
      preload: path.join(__dirname, "preload.cjs"),
    },
  });

  if (isDev) {
    mainWindow.loadURL("http://localhost:5173");
    mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, "../dist/index.html"));
  }
};

// Allow self-signed certificates for local backend HTTPS
app.on("certificate-error", (event, webContents, url, error, certificate, callback) => {
  // Only allow for localhost/127.0.0.1 connections to our backend
  if (url.startsWith("https://localhost:") || url.startsWith("https://127.0.0.1:")) {
    log(`Allowing self-signed certificate for: ${url}`);
    event.preventDefault();
    callback(true);
  } else {
    callback(false);
  }
});

app.whenReady().then(async () => {
  try {
    // Start backend first, then window
    await Promise.race([
      startBackend(),
      new Promise((_, reject) => setTimeout(() => reject("Backend timeout"), 10000))
    ]);
    createWindow();
  } catch (err) {
    dialog.showErrorBox("Startup Failed", `Could not start backend: ${err}`);
    app.quit();
  }
});

app.on("will-quit", () => {
  if (apiProcess) apiProcess.kill();
  if (process.platform !== "darwin") app.quit();
});