import { app, BrowserWindow, dialog, ipcMain } from "electron";
import * as path from "path";
import { spawn, ChildProcess } from "child_process";
import * as fs from "fs";


let mainWindow: BrowserWindow | null = null;
let apiProcess: ChildProcess | null = null;

// --- Helper: Path Resolution ---
const isDev = !app.isPackaged;

const getBinPath = () => {
  if (isDev) {
    // In dev, we look for python in the environment
    return process.platform === "win32" ? "python" : "python3";
  }
  // In production, point to the executable generated by PyInstaller
  // This assumes you've put your binary in the 'resources' folder
  const binName = process.platform === "win32" ? "api.exe" : "api";
  return path.join(process.resourcesPath, "backend", binName);
};

const getBackendRoot = () => {
  return isDev 
    ? path.join(process.cwd(), "backend") 
    : path.join(process.resourcesPath, "backend");
};

// --- Logging ---
const log = (msg: string) => {
  const logFile = path.join(app.getPath("userData"), "app.log");
  const logMsg = `[${new Date().toISOString()}] ${msg}\n`;
  console.log(logMsg);
  fs.appendFileSync(logFile, logMsg);
};

// --- Backend Management ---
const startBackend = async () => {
  return new Promise<void>((resolve, reject) => {
    const pythonBin = getBinPath();
    const backendDir = getBackendRoot();
    const userDataPath = app.getPath("userData");
    
    log(`Starting backend with: ${pythonBin} in ${backendDir}`);
    log(`User Data Path for SQLite: ${userDataPath}`);

    // Fix permissions for macOS/Linux in production before spawning
    if (!isDev && process.platform !== "win32") {
      try {
        log("Ensuring backend binary is executable...");
        fs.chmodSync(pythonBin, 0o755);
      } catch (e: any) {
        log(`Warning: Could not set permissions on binary: ${e.message}`);
      }
    }

    let args: string[] = [];
    
    if (isDev) {
      args = ["-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8833"];
    } else {
      args = ["--port", "8833"]; 
    }

    apiProcess = spawn(pythonBin, args, {
      cwd: backendDir,
      env: { 
        ...process.env, 
        PYTHONUNBUFFERED: "1",
        APP_USER_DATA: userDataPath 
      },
      shell: false 
    });

    // Unified log handler to catch signals regardless of which stream Python uses
    const handleOutput = (data: any) => {
      const output = data.toString();
      log(`[API] ${output}`);

      // We look for "Uvicorn running" OR "Application startup complete" (the FastAPI signal)
      if (output.includes("Uvicorn running") || output.includes("Application startup complete")) {
        log("Backend signal received: Server is ready.");
        resolve();
      }
    };

    apiProcess.stdout?.on("data", handleOutput);
    apiProcess.stderr?.on("data", handleOutput);

    apiProcess.on("error", (err) => {
      log(`Failed to spawn backend: ${err.message}`);
      reject(err);
    });

    // Increased timeout to 30s to account for SQLite migration time on first run
    const startupTimeout = setTimeout(() => {
      log("Backend startup timeout reached. Attempting to load window anyway...");
      resolve();
    }, 30000);

    // Clean up timeout if we resolve early
    apiProcess.on("exit", () => clearTimeout(startupTimeout));
  });
};

// --- Window Management ---
const createWindow = () => {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    webPreferences: {
      contextIsolation: true,
      preload: path.join(__dirname, "preload.cjs"),
    },
  });

  if (isDev) {
    mainWindow.loadURL("http://localhost:5173");
    mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, "../dist/index.html"));
  }
};

app.whenReady().then(async () => {
  try {
    // Start backend first, then window
    await Promise.race([
      startBackend(),
      new Promise((_, reject) => setTimeout(() => reject("Backend timeout"), 10000))
    ]);
    createWindow();
  } catch (err) {
    dialog.showErrorBox("Startup Failed", `Could not start backend: ${err}`);
    app.quit();
  }
});

app.on("will-quit", () => {
  if (apiProcess) apiProcess.kill();
  if (process.platform !== "darwin") app.quit();
});