"""Initial SQLite migration

Revision ID: daf2ec8b9456
Revises: 
Create Date: 2026-01-30 15:15:01.987197

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'daf2ec8b9456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_key'), ['key'], unique=True)

    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_name', sa.String(length=255), nullable=False),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('size_major', sa.Float(), nullable=True),
    sa.Column('size_minor', sa.Float(), nullable=True),
    sa.Column('constellation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objects_primary_name'), ['primary_name'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index('ix_projects_status', ['status'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('directory_path', sa.String(length=1024), nullable=False),
    sa.Column('date_taken', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    sa.Column('filter_name', sa.String(length=50), nullable=True),
    sa.Column('telescope', sa.String(length=255), nullable=True),
    sa.Column('camera', sa.String(length=255), nullable=True),
    sa.Column('gain', sa.Integer(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('binning', sa.String(length=10), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('pixel_size_x', sa.Float(), nullable=True),
    sa.Column('pixel_size_y', sa.Float(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('fov_width', sa.Float(), nullable=True),
    sa.Column('fov_height', sa.Float(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('fits_header', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('ix_images_date_taken', ['date_taken'], unique=False)
        batch_op.create_index('ix_images_file_path', ['file_path'], unique=False)
        batch_op.create_index('ix_images_filter_name', ['filter_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_id'), ['id'], unique=False)
        batch_op.create_index('ix_images_object_id', ['object_id'], unique=False)

    op.create_table('object_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('catalog', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_aliases_alias_name'), ['alias_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_aliases_id'), ['id'], unique=False)

    op.create_table('project_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('exposure_goals', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'object_id', name='uq_project_target')
    )
    with op.batch_alter_table('project_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_targets_id'), ['id'], unique=False)
        batch_op.create_index('ix_project_targets_object_id', ['object_id'], unique=False)
        batch_op.create_index('ix_project_targets_project_id', ['project_id'], unique=False)

    op.create_table('image_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sa.String(length=50), nullable=False),
    sa.Column('angular_distance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'object_id', name='uq_image_object')
    )
    with op.batch_alter_table('image_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_objects_id'), ['id'], unique=False)

    op.create_table('project_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('added_manually', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'image_id', name='uq_project_image')
    )
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_images_id'), ['id'], unique=False)
        batch_op.create_index('ix_project_images_image_id', ['image_id'], unique=False)
        batch_op.create_index('ix_project_images_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.drop_index('ix_project_images_project_id')
        batch_op.drop_index('ix_project_images_image_id')
        batch_op.drop_index(batch_op.f('ix_project_images_id'))

    op.drop_table('project_images')
    with op.batch_alter_table('image_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_objects_id'))

    op.drop_table('image_objects')
    with op.batch_alter_table('project_targets', schema=None) as batch_op:
        batch_op.drop_index('ix_project_targets_project_id')
        batch_op.drop_index('ix_project_targets_object_id')
        batch_op.drop_index(batch_op.f('ix_project_targets_id'))

    op.drop_table('project_targets')
    with op.batch_alter_table('object_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_aliases_id'))
        batch_op.drop_index(batch_op.f('ix_object_aliases_alias_name'))

    op.drop_table('object_aliases')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_object_id')
        batch_op.drop_index(batch_op.f('ix_images_id'))
        batch_op.drop_index('ix_images_filter_name')
        batch_op.drop_index('ix_images_file_path')
        batch_op.drop_index('ix_images_date_taken')

    op.drop_table('images')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_status')
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objects_primary_name'))
        batch_op.drop_index(batch_op.f('ix_objects_id'))

    op.drop_table('objects')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_key'))
        batch_op.drop_index(batch_op.f('ix_configurations_id'))

    op.drop_table('configurations')
    # ### end Alembic commands ###
